// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {installer} from '../models';

export function Install(arg1:installer.Request):Promise<string>;

export function TestSSH(arg1:installer.Request):Promise<string>;

export function Update(arg1:installer.Request):Promise<string>;

export function ServerTop(arg1:installer.Request):Promise<string>;
