// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Install(arg1) {
  return window['go']['guiservice']['App']['Install'](arg1);
}

export function TestSSH(arg1) {
  return window['go']['guiservice']['App']['TestSSH'](arg1);
}

export function Update(arg1) {
  return window['go']['guiservice']['App']['Update'](arg1);
}

export function ServerTop(arg1) {
  return window['go']['guiservice']['App']['ServerTop'](arg1);
}
