name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          check-latest: true
      - name: install_wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: init_wails
        run: wails build
      - name: build
        run: go build ./...
      - name: test
        run: go test -race ./...
